class navigationConfig {
  static navigationConfigArr() {
    const dataArr = [
      {
        id: "stockMaster",
        title: "Stock Master",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "itemType",
            title: "Main Item Type",
            type: "item",
            url: "/dashboard/masters/itemtype",
            isAccessible: true,
          },
          {
            id: "stockGroup",
            title: "Stock Group",
            type: "item",
            url: "/dashboard/masters/stockgroup",
            isAccessible: true,
          },
          {
            id: "stkName",
            title: "Stock Name",
            type: "item",
            url: "/dashboard/masters/stockname",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-1",
      },
      {
        id: "userMaster",
        title: "Users Masters",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "clients",
            title: "Client / Party",
            type: "item",
            url: "/dashboard/masters/clients",
            isAccessible: true,
          },
          {
            id: "b2cclients",
            title: "B2C Client",
            type: "item",
            url: "/dashboard/masters/btocclient",
            isAccessible: true,
          },
          {
            id: "vendors",
            title: "Vendors",
            type: "item",
            url: "/dashboard/masters/vendors",
            isAccessible: true,
          },
          {
            id: "categories",
            title: "Category (Product(S) Type)",
            type: "item",
            url: "/dashboard/masters/productcategory",
            isAccessible: true,
          },
          {
            id: "jobWorkers",
            title: "Job Worker",
            type: "item",
            url: "/dashboard/masters/jobworker",
            isAccessible: true,
          },
          {
            id: "salesmen",
            title: "Salesman",
            type: "item",
            url: "/dashboard/masters/salesman",
            isAccessible: true,
          },
          {
            id: "systemUser",
            title: "System User",
            type: "item",
            url: "/dashboard/masters/systemuser",
            isAccessible: true,
          },
          {
            id: "userRole",
            title: "User Role",
            type: "item",
            url: "/dashboard/masters/userrole",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-2",
      },
      {
        id: "departmentMaster",
        title: "Department Master",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "department",
            title: "Department",
            type: "item",
            url: "/dashboard/masters/department",
            isAccessible: true,
          },
          {
            id: "process",
            title: "Process",
            type: "item",
            url: "/dashboard/masters/process",
            isAccessible: true,
          },
          {
            id: "processline",
            title: "Process Line",
            type: "item",
            url: "/dashboard/masters/processline",
            isAccessible: true,
          },
          {
            id: "workstation",
            title: "Work Station",
            type: "item",
            url: "/dashboard/masters/workstation",
            isAccessible: true,
          },
          {
            id: "hallmarkstation",
            title: "Hallmark Station",
            type: "item",
            url: "/dashboard/masters/hallmarkstation",
            isAccessible: true,
          },
          {
            id: "variant_attribute",
            title: "Variant Attribute",
            type: "item",
            url: "/dashboard/masters/variantattribute",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-3",
      },
      {
        id: "designer",
        title: "Designer",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "designeruser",
            title: "Design User",
            type: "item",
            url: "/dashboard/masters/designuser",
            isAccessible: true,
          },
          {
            id: "designerRole",
            title: "Designer Role",
            type: "item",
            url: "/dashboard/masters/designerrole",
            isAccessible: true,
          },
          {
            id: "designerlocation",
            title: "Designer Location",
            type: "item",
            url: "/dashboard/masters/designerlocation",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-4",
      },
      {
        id: "rateProfiles",
        title: "Rate Profiles",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "salesRateProfile",
            title: "Sales Rate Profile",
            type: "item",
            url: "/dashboard/masters/salesrateprofile",
            isAccessible: true,
          },
          {
            id: "taggingRateProfile",
            title: "Tagging Rate Profile",
            type: "item",
            url: "/dashboard/masters/taggingrateprofile",
            isAccessible: true,
          },
          {
            id: "jobworkervendorrateprof",
            title: "Job Worker & Vendor Rate Profile",
            type: "item",
            url: "/dashboard/masters/jobworkervendorrateprof",
            isAccessible: true,
          },
          {
            id: "workstationprofile",
            title: "Work Station Rate Profile",
            type: "item",
            url: "/dashboard/masters/workstationrateprof",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-5",
      },
      {
        id: "settings",
        title: "Settings",
        type: "collapse",
        isAccessible: true,
        children: [
          {
            id: "SiteSettings",
            title: "Site Settings",
            type: "item",
            url: "/dashboard/masters/SiteSettings",
            isAccessible: true,
          },
          {
            id: "TagSystem",
            title: "Tag System",
            type: "item",
            url: "/dashboard/masters/TagSystem",
            isAccessible: true,
          },
          {
            id: "TagPrinter",
            title: "Tag Printer",
            type: "item",
            url: "/dashboard/masters/TagPrinter",
            isAccessible: true,
          },
          {
            id: "HSNMasters",
            title: "HSN Master",
            type: "item",
            url: "/dashboard/masters/HSNMaster",
            isAccessible: true,
          },

          {
            id: "lotwgtvariation",
            title: "Weight Tolerance",
            type: "item",
            url: "/dashboard/masters/weighttolerance",
            isAccessible: true,
          },
          {
            id: "finishPurity",
            title: "Finish Purity Master",
            type: "item",
            url: "/dashboard/masters/finishpurity",
            isAccessible: true,
          },
          {
            id: "settingmethod",
            title: "Setting Method",
            type: "item",
            url: "/dashboard/masters/settingmethod",
            isAccessible: true,
          },
          {
            id: "bagging",
            title: "Bagging",
            type: "item",
            url: "/dashboard/masters/bagging",
            isAccessible: true,
          },
          {
            id: "typeofsetting",
            title: "Type of Setting",
            type: "item",
            url: "/dashboard/masters/typeofsetting",
            isAccessible: true,
          },
          {
            id: "ledgerrate",
            title: "TCS / TDS Ledger Rate",
            type: "item",
            url: "/dashboard/masters/ledgerrate",
            isAccessible: true,
          },
          {
            id: "goldRate",
            title: "Today's Gold Rate",
            type: "item",
            url: "/dashboard/masters/goldrate",
            isAccessible: true,
          },
          {
            id: "hallmarkCharges",
            title: "Hallmark Charges",
            type: "item",
            url: "/dashboard/masters/hallmarkcharges",
            isAccessible: true,
          },
          {
            id: "country",
            title: "Country",
            type: "item",
            url: "/dashboard/masters/Country",
            isAccessible: true,
          },
          {
            id: "state",
            title: "State",
            type: "item",
            url: "/dashboard/masters/state",
            isAccessible: true,
          },
          {
            id: "city",
            title: "City",
            type: "item",
            url: "/dashboard/masters/City",
            isAccessible: true,
          },
        ],
      },
      {
        type: "divider",
        id: "divider-6",
      },
    ];
    return dataArr;
  }
}

export default navigationConfig;
